### PR TITLE
procedural-masquerade is not MPL

### PR DESCRIPTION
**Pull request by SimonSapin**
CC https://github.com/servo/rust-cssparser/pull/201#issuecomment-343659915

This change is [Reviewable](https://reviewable.io/reviews/servo/rust-cssparser/202)

### CODE REVIEW

**Comment by SimonSapin** [comment]
@ignatenkobrain, how does this look?

**Comment by ignatenkobrain** [comment]
@SimonSapin looks awesome!

**Comment by SimonSapin** [comment]
Published 0.1.5

**Comment by SimonSapin** [comment]
Out of curiosity, what are you packaging that depends on this crate?

**Comment by ignatenkobrain** [comment]
@SimonSapin extprim_literals <- extprim <- syntex_syntax

I know that syntex is dead, but latest "old" rustfmt still depends on it. And we don't package nightly compiler, only stable.

In any case, it is also dependency of cssparser which is used by servo, isn't it? I would like to package servo one day as well. Not sure if it's used by FF too (probably some of deps of stylo..)

**Pull request merged**
