### PR TITLE
Include source location in param of rule parsers

### PR DESCRIPTION
**Pull request by upsuper**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-cssparser/226)

### CODE REVIEW

**Comment by upsuper** [comment]
cc servo/servo#20527

**Comment by upsuper** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1471104 for the Gecko/Servo side change.

**Comment by SimonSapin** [comment]
Looks good.

@bors-servo r+

**Pull request merged**
