### PR TITLE
Clamp to MAX / INFINITY rather than panic on overflow in number parsing

### PR DESCRIPTION
**Pull request by SimonSapin**
r? @jdm

This also changes the numeric types in tokens from `f64` / `i64` to `f32` / `i32`, which might requires some changes in Servo.

### CODE REVIEW

**Comment by jdm** [comment]
I haven't looked at the merge commit; the rest look fine to me. Should I be looking at the merge?

**Comment by SimonSapin** [comment]
The merge includes some fairly simple conflict resolutions, as well as a replacement of `Float::powf` with `f64::powf` (corresponding to a Rust upgrade).

By the way, the commit to use in Servo (unless Servo does another Rust upgrade) is the one before the merge.

**Comment by jdm** [comment]
I don't think there's a burning need to adopt these changes before the next upgrade. Looks good to me!

**Comment by SimonSapin** [comment]
> Looks good to me!

I’ll take that as r+ :)

**Pull request merged**
