### PR TITLE
Don't heap-allocate a tokenizer for top-level parsing.

### PR DESCRIPTION
**Pull request by emilio**
r? @SimonSapin

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-cssparser/124)

### CODE REVIEW

**Comment by SimonSapin** [comment]
IIRC when I wrote this I did not expect creating new parsers to be hot. Is it for CSSOM setters?

**Comment by SimonSapin** [comment]
Ah you already replied yes on IRC :)

@bors-servo r+

**Comment by emilio** [comment]
@bors-servo r-

I'll update the MaybeOwned docs.

**Comment by SimonSapin** [comment]
(MaybeOwned is not public, but yeah)

@bors-servo r+

**Pull request merged**
