### PR TITLE
Remove Column token.

### PR DESCRIPTION
**Pull request by heycam**
It no longer exists in the css-syntax spec.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-cssparser/203)

### CODE REVIEW

**Comment by SimonSapin** [comment]
This is a breaking API change, please make sure you increment the version number accordingly before publishing on crates.io. (Ideally that would have been part of the PR.)

**Comment by heycam** [comment]
Thanks, I'll try to remember about version bumps next time.

**Pull request merged**
