### PR TITLE
Refactoring, better ability to use `cssparser-color` as a separate crate.

### PR DESCRIPTION
**Pull request by chipnertkj**
- Use case for better `cssparser-color` separation:
Access to private implementation items for parsers and other software using the crate.
- Example use case and motivation:
My own project. I use the crate to serialize and deserialize CSS3-compatible color data from user input and config files. This was impossible without these changes.
- Serde impls for `color` crate items are gated by a new `serde` feature in the inner crate.
- A few public functions were adjusted with new names, as suggested by `clippy` - caused a semantic conflict with std's `Iterator`.
- General refactoring. 

All checks passed on my fork, but I'm not familiar with the guidelines for commits for this repository. It's my first one here. I hope it's up to expectations. 😁
If something's up, be sure to comment.

### CODE REVIEW

**Comment by chipnertkj** [comment]
Apparently part of the changes were also requested here: https://github.com/servo/rust-cssparser/issues/376

**Review by emilio — CHANGES_REQUESTED** [review]
A lot of these look good but can we avoid the breaking changes in cssparser? Seem unnecessary to me unless I'm missing something.

**Comment by chipnertkj** [comment]
@emilio That's absolutely doable, it's just that I see valid reasoning in the `clippy` hint, enough of it to increase the minor version, especially since the project isn't in a mature state yet. Realistically, would that change be problematic? Genuine question.

**Comment by emilio** [comment]
Yeah, the tokenizer uses the `try` prefix (well, now `try_parse`) for stuff that rewinds, so `try_next` doesn't feel necessarily like a great name. Also, in a sense the tokenizer / parser's `next()` is basically an `Iterator` (over the tokens), even if it returns an extra info for the errors.

It'd also mean we'd have to rewrite [quite a few callers](https://searchfox.org/mozilla-central/search?q=symbol:S_rs_parser%2FParser%23next().&redirect=false). That's not a huge deal if the improvement is clear, but for me at least `try_next` is just a longer and more confusing name...

In any case, those changes should probably be their own PR. I'd prefer to split the different high-level changes in different PRs if that's possible, so that they can be reviewed / merged independently.

**Comment by chipnertkj** [comment]
I see, sure thing! I'll revert the naming and version changes as soon as possible.

**Comment by chipnertkj** [comment]
Okay, that should be it.

**Review by emilio — APPROVED** [review]
Thanks, this looks great, but the commit history is a bit of a mess. I sent https://github.com/servo/rust-cssparser/pull/378 with it cleaned-up.

**Pull request closed without merging**
