### PR TITLE
Bump version to 0.30.0

### PR DESCRIPTION
**Pull request by wusyong**
Sorry I forgot to add the version bump in previous PR.
~~I bump the patch version since this doesn't add or change anything in cssparser itself?~~
Just realized this changed the minimum rust version.

### CODE REVIEW

**Comment by emilio** [comment]
@bors-servo delegate+

r=me with that change. You can at-bors-servo r=emilio yourself :)

**Comment by wusyong** [comment]
r=emilio

**Comment by wusyong** [comment]
@emilio How do we publish latest version to crates.io? Is there a command for bots?

**Comment by emilio** [comment]
Someone with the right permissions needs to do it. I just did :)

**Pull request merged**
