### PR TITLE
Update phf to 0.8

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by SimonSapin** [comment]
`getrandom` failed to build on 1.31, https://github.com/rust-random/getrandom#minimum-supported-rust-version lists 1.32

**Comment by nox** [comment]
> `getrandom` failed to build on 1.31, https://github.com/rust-random/getrandom#minimum-supported-rust-version lists 1.32

I know, which is why I want the `MaybeUninit` patch to land because it already increases minimum Rust version.

**Pull request merged**
