### PR TITLE
Parse 8, 4 digits hex notations

### PR DESCRIPTION
**Pull request by disjukr**
http://drafts.csswg.org/css-color/#hex-notation

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-cssparser/80)

### CODE REVIEW

**Comment by simnalamburt** [comment]
:+1:

**Comment by SimonSapin** [comment]
Looks good, thanks!

**Comment by metajack** [comment]
@SimonSapin bors-servo should be working on this repo.

**Comment by SimonSapin** [comment]
Oops, I need to remember to use it.

**Pull request merged**
