### PR TITLE
Record whether viewport percentage dimensions are seen

### PR DESCRIPTION
**Pull request by mbrubeck**
Used to tell Servo to recalulate styles on window resize (servo/servo#8754).

r? @SimonSapin

[Review on Reviewable](https://reviewable.io/reviews/servo/rust-cssparser/99)

### CODE REVIEW

**Comment by SimonSapin** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/tokenizer.rs, line 226 \[r1\]](https://reviewable.io:443/reviews/servo/rust-cssparser/99#-KDAyfnXml6wcsEezjnQ:-KDAyfnXml6wcsEezjnR:-1134760866) ([raw file](https://github.com/servo/rust-cssparser/blob/d9dd56b7a056b84377c44da63b390a32f45e5098/src/tokenizer.rs#L226)):*
Nit: maybe rename the `VarFunction` enum and use it for both? I don’t have a good name to suggest though :/

---

*[src/tokenizer.rs, line 810 \[r1\]](https://reviewable.io:443/reviews/servo/rust-cssparser/99#-KDAz32VZS2qr29Lgjsb:-KDAz32VZS2qr29Lgjsc:-922908380) ([raw file](https://github.com/servo/rust-cssparser/blob/d9dd56b7a056b84377c44da63b390a32f45e5098/src/tokenizer.rs#L810)):*
This needs to be an ASCII case-insensitive match. Unfortunately `match_ignore_ascii_case!` doesn’t support alternates with `|` and can’t easily since `x | y` is a valid expression. Maybe use `name.eq_ignore_ascii_case(…)` directly?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-cssparser/99)*

**Comment by mbrubeck** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/tokenizer.rs, line 226 \[r1\]](https://reviewable.io:443/reviews/servo/rust-cssparser/99#-KDAyfnXml6wcsEezjnQ:-KDB3p10MDVPhHoBedd6:-499146009) ([raw file](https://github.com/servo/rust-cssparser/blob/d9dd56b7a056b84377c44da63b390a32f45e5098/src/tokenizer.rs#L226)):*
Done.

---

*[src/tokenizer.rs, line 810 \[r1\]](https://reviewable.io:443/reviews/servo/rust-cssparser/99#-KDAz32VZS2qr29Lgjsb:-KDB3qPrEIqd4HUWMsH_:-499146009) ([raw file](https://github.com/servo/rust-cssparser/blob/d9dd56b7a056b84377c44da63b390a32f45e5098/src/tokenizer.rs#L810)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-cssparser/99)*

**Comment by SimonSapin** [comment]
@bors-servo r+

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/rust-cssparser/99#-:-KDBCyUuFTwRASNSGkqC:1236647940)*

**Comment by SimonSapin** [comment]
I’ve hit "Synchronize" in http://build.servo.org/homu/queue/rust-cssparser

@bors-servo r+

**Comment by SimonSapin** [comment]
Published v0.5.5 on crates.io

**Pull request merged**
