### PR TITLE
Avoid boundary check in parse_n_dash_digits

### PR DESCRIPTION
**Pull request by upsuper**
Fix [bug 1404678](https://bugzilla.mozilla.org/show_bug.cgi?id=1404678).

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-cssparser/199)

### CODE REVIEW

**Comment by upsuper** [comment]
Could you publish a new version to crates.io?

**Comment by SimonSapin** [comment]
Done: https://crates.io/crates/cssparser/0.21.3

**Comment by upsuper** [comment]
Thanks.

**Pull request merged**
