### PR TITLE
deps: bump encoding_rs to 0.8

### PR DESCRIPTION
**Pull request by ignatenkobrain**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-cssparser/227)

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
ping @SimonSapin

**Comment by emilio** [comment]
This looks good to me. Thanks @ignatenkobrain :)

@bors-servo r+

**Comment by emilio** [comment]
The failure is not your fault. I opened https://github.com/servo/rust-cssparser/pull/238 to address it, and we can merge after that lands.

**Pull request merged**
