### PR TITLE
Return meaningful error values when parsing

### PR DESCRIPTION
**Pull request by jdm**
This is #143 with an extra commit added to accommodate changes requested in https://github.com/servo/servo/pull/16752.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-cssparser/155)

### CODE REVIEW

**Comment by jdm** [comment]
This should not be merged until https://github.com/servo/servo/pull/16752 is ready to merge.

**Comment by SimonSapin** [comment]
r+ with unit tests fixed. (Travis-CI fails.)

**Comment by SimonSapin** [comment]
Reviewed 4 of 8 files at r2, 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/parser.rs, line 75 at r4](https://reviewable.io:443/reviews/servo/rust-cssparser/155#-Km3IETRVPayQv1AE-g5:-Km3IETRVPayQv1AE-g6:b-sb0vpk) ([raw file](https://github.com/servo/rust-cssparser/blob/070c029bce44143002abfece3c6157d8d44070fe/src/parser.rs#L75)):*
> ```Rust
> 
> impl<'t> ops::Deref for ParserInput<'t> {
>     type Target = Tokenizer<'t>;
> ```

This makes the tokenizer effectively public. Please remove the `Deref` impls (and add `.0` as needed in this file.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/servo/rust-cssparser/155)*

**Pull request merged**
