### PR TITLE
Minor rules and declaration cleanups.

### PR DESCRIPTION
**Pull request by emilio**

### CODE REVIEW

**Comment by emilio** [comment]
@tiaanl @SimonSapin @jdm any objection on bumping MSRV to 1.63 which fixes the bugs that we were working around in #254?

Seems already old-ish enough, and allows #256 to get through too. I'm going to rejigger some of this code for nesting and it'd be good not having to think about the weird lifetime inference bug.

**Comment by SimonSapin** [comment]
No objection!

**Comment by emilio** [comment]
@bors-servo r+

Alright then :)

**Comment by emilio** [comment]
Well actually, since there's a release pending, let me do that first. @bors-servo r-

**Pull request merged**
